name: KotlinPlugin
version: '${project.version}'
main: me.wakka.kotlinplugin.KotlinPlugin
api-version: 1.19
author: Wakka
commands:
  showitem:
    permission: "kp.showitem"
    description: show item in slot with a message
  task:
    permission: "kp.task"
    description: testing tasks